name: Initialise tljh

on:
  push:
    paths:
      - 'ServerID.md' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Install sshpass
      run: |
        sudo apt-get install -y sshpass
      

    # Runs a set of commands using the runners shell
    - name: Install conda packages from packages.yml file
      env:  
        SSHPASS: ${{ secrets.DROPLET_PASS }}
        HUBADMIN: ${{ secrets.HUBADMIN_USER }}
        HUBADMIN_PASS: ${{ secrets.HUBADMIN_PASSWORD }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} hostname
        sshpass -e ssh root@${{ secrets.DROPLET_IP }} "curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py | sudo python3 -  --admin $HUBADMIN:$HUBADMIN_PASS" 
